### ISSUE TITLE
Installation and pytest running failure

### ISSUE THREAD

**Issue by shahriar49** [repository-preservation/lcmap-pyccd#49]
Hi,
I followed the installation guidelines and installed device and test dependencies, but got a red warning during the last part saying that `'pytest-profiling 1.6.0 has requirement pytest<4.0.0, but you'll have pytest 4.3.0 which is incompatible.'` Then I ran the pytest and got below error. I also tried to run the Python Notebook but it failed to load module aniso8601, while it was installed in the site-packages. Could you please help me resolve this issue?

```
Traceback (most recent call last):
  File "c:\users\shhey\pyccd\.venv\lib\site-packages\pluggy\manager.py", line 274, in load_setuptools_entrypoints
    plugin = ep.load()
  File "c:\users\shhey\pyccd\.venv\lib\site-packages\pkg_resources\__init__.py", line 2410, in load
    self.require(*args, **kwargs)
  File "c:\users\shhey\pyccd\.venv\lib\site-packages\pkg_resources\__init__.py", line 2433, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "c:\users\shhey\pyccd\.venv\lib\site-packages\pkg_resources\__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pytest 4.3.0 (c:\users\shhey\pyccd\.venv\lib\site-packages), Requirement.parse('pytest<4.0.0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\shhey\pyccd\.venv\Scripts\pytest.exe\__main__.py", line 9, in <module>
  File "c:\users\shhey\pyccd\.venv\lib\site-packages\_pytest\config\__init__.py", line 61, in main
    config = _prepareconfig(args, plugins)
  File "c:\users\shhey\pyccd\.venv\lib\site-packages\_pytest\config\__init__.py", line 196, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "c:\users\shhey\pyccd\.venv\lib\site-packages\pluggy\hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\shhey\pyccd\.venv\lib\site-packages\pluggy\manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\shhey\pyccd\.venv\lib\site-packages\pluggy\manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\shhey\pyccd\.venv\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "c:\users\shhey\pyccd\.venv\lib\site-packages\_pytest\helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "c:\users\shhey\pyccd\.venv\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\shhey\pyccd\.venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\shhey\pyccd\.venv\lib\site-packages\_pytest\config\__init__.py", line 655, in pytest_cmdline_parse
    self.parse(args)
  File "c:\users\shhey\pyccd\.venv\lib\site-packages\_pytest\config\__init__.py", line 871, in parse
    self._preparse(args, addopts=addopts)
  File "c:\users\shhey\pyccd\.venv\lib\site-packages\_pytest\config\__init__.py", line 817, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "c:\users\shhey\pyccd\.venv\lib\site-packages\pluggy\manager.py", line 280, in load_setuptools_entrypoints
    message="Plugin %r could not be loaded: %s!" % (ep.name, e),
pluggy.manager.PluginValidationError: Plugin 'profiling' could not be loaded: (pytest 4.3.0 (c:\users\shhey\pyccd\.venv\lib\site-packages), Requirement.parse('pytest<4.0.0'))!

```

**Comment by Brown-cugb** [comment]
Dear,
When I Install dev dependencies,after I does the step"Install jupyter notebook and line_profiler",It says 

File "setup.py" not found. Directory cannot be installed in editable mode: /home/hanlele/pyccd

Could you help me to do the pytest? I also need to use lcmap-pyccd to do my research,and could you give some advice to use it?
Thank you very much!

**Comment by shahriar49** [comment]
Actually I didn't try to install profiler and do pytest anymore. I just installed the required modules 
numpy, scipy, scikit-learn, aniso8601, matplotlib, lcmap-pyccd, and jupyter (I needed to reinstall tornado with pip install "tornado<6", otherwise the html browser cannot connect to kernel currently) . Then I ran the provided notebooks and it worked!
